Repository PROJECT-BUSAN-6th/bokjido-backend, pull requests merged in 2023-09, with the labels that each got.

#26 Feat[#20] 건물 리뷰 및 건물 탐색 API 구현
  bokjido/src/main/java/com/projectbusan/bokjido/auth/JwtTokenProvider.java
  bokjido/src/main/java/com/projectbusan/bokjido/controller/FacilityController.java
  bokjido/src/main/java/com/projectbusan/bokjido/dto/FacilityReviewDTO.java
  bokjido/src/main/java/com/projectbusan/bokjido/entity/FacilityReview.java
  bokjido/src/main/java/com/projectbusan/bokjido/exception/ErrorCode.java
  bokjido/src/main/java/com/projectbusan/bokjido/repository/FacilityRepository.java
  bokjido/src/main/java/com/projectbusan/bokjido/repository/FacilityReviewRepository.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/FacilityService.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/WelfareFacility.java
Labels: API

#27 Feat[#21] 복지서비스 맞춤 추천 API 구현
  bokjido/src/main/java/com/projectbusan/bokjido/controller/BenefitController.java
  bokjido/src/main/java/com/projectbusan/bokjido/dto/AuthDTO.java
  bokjido/src/main/java/com/projectbusan/bokjido/entity/User.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/BenefitsService.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/BenefitsServiceImpl.java
Labels: feat, API

#29 fix[#17]: Get요청을 쿼리 파라미터로만 하도록 수정
  bokjido/src/main/java/com/projectbusan/bokjido/controller/BenefitController.java
  bokjido/src/main/java/com/projectbusan/bokjido/dto/BenefitRequestDTO.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/BenefitsService.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/BenefitsServiceImpl.java
Labels: fix

#31 Fix[#26] Feat[#30] 복지시설 필터 API 구현
  bokjido/src/main/java/com/projectbusan/bokjido/config/CorsConfig.java
  bokjido/src/main/java/com/projectbusan/bokjido/controller/FacilityController.java
  bokjido/src/main/java/com/projectbusan/bokjido/repository/FacilityRepository.java
  bokjido/src/main/java/com/projectbusan/bokjido/service/WelfareFacility.java
Labels: feat, fix, API
